#spring.application.name=githubMcpServer
#
##-Dspring.ai.mcp.server.stdio=true
#
##spring.main.banner-mode=off
##spring.main.web-application-type=none
#
#logging.pattern.console=
#logging.level.root=ERROR
#
#
#gemini.api.key = ${GEMINI_API_KEY}
#github.token=${GITHUB_TOKEN}
#github.default-owner=AntoThilifan2026
#github.default-branch=main
#
#spring.ai.mcp.server.enabled=true


spring.application.name=githubMcpServer

logging.level.root=INFO

gemini.api.key=${GEMINI_API_KEY}
github.token=${GITHUB_TOKEN}
github.default-owner=AntoThilifan2026
github.default-branch=main

spring.ai.mcp.server.enabled=false